server:
  port: 8083
spring:
  application:
    name: task-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/devboard}
app:
  auth-url: ${AUTH_URL:http://localhost:8081}
  project-url: ${PROJECT_URL:http://localhost:8082}
