apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-service
    {{ include "devboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ include "devboard.image" (dict "root" . "repo" .Values.auth.image.repository) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.service.port }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: mongo-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: jwt-secret
          resources:
            {{ toYaml .Values.auth.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /auth/actuator/health
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/actuator/health
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
