apiVersion: v1
kind: Secret
metadata:
  name: devboard-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.mongodb.uri | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
